const GRAPHICS_REFRESH_TIMER_INTERVAL = 10;
const POINTS_TEXT_LOCATION = new Point(10, 30);
const POINTS_TEXT_COLOR = "#00AA00";
const POINTS_TEXT_FONT = "30px Tahoma";
const POINTS_TEXT = "Points: ";
const GAME_START_TEXT_COLOR = "#0000AA";
const GAME_START_TEXT_FONT = "120px Tahoma";
const GAME_START_TEXT = "Jetpack Man";
const GAME_START_SUB_TEXT_COLOR = "#0000AA";
const GAME_START_SUB_TEXT_FONT = "30px Tahoma";
const GAME_START_SUB_TEXT = "Click to play";
const GAME_OVER_TEXT_COLOR = "#AA0000";
const GAME_OVER_TEXT_FONT = "100px Tahoma";
const GAME_OVER_TEXT = "Game over!";
const GAME_OVER_SUB_TEXT_COLOR = "#AA0000";
const GAME_OVER_SUB_TEXT_FONT = "30px Tahoma";
const GAME_OVER_SUB_TEXT = "Click to play again";
const GRAVITY = -1;
const MAN_MOVEMENT_TIMER_INTERVAL = 10;
const METEORS_MOVEMENT_TIMER_INTERVAL = 5;
const METEORS_LIMITED_ARRAY_MAX_CAPACITY = 10;

const FIRST_METEOR_INITIAL_X_LOCATION = 2000;
const METEORS_X_SPEED = 10;
const X_DISTANCE_BETWEEN_METEORS = 500;
const METEORS_MOVEMENT_AMOUNT = -6;

const MAN_INITIAL_LOCATION = new Point(300, 512);
const MAN_INITIAL_Y_SPEED = 0;

const JETPACK_ACCELERATION = 2;
const JETPACK_MAX_Y_SPEED = 10;
